### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by manuel-rubio** [shufo/fcmex#36]
This URL is not working anymore:
https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages

Instead, I guess it's working this another one:
https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages

**Comment by shufo** [comment]
@manuel-rubio Thanks for reporting issue! I just fixed link at https://github.com/shufo/fcmex/commit/26b4dc9dc606862f60f25ce39ac2d844a027dd35.
